name: qnverter # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Python application for quick text conversions. # 79 char long summary
description: |
  its a quick way of converting any textbased contents in a fast and easy way,
  wich also means you dont't have to give up your data to some website on the
  internet just to be able to convert a few json files.
  The entire application is written in pure python and uses the PyQt module to generate the GUI.
  You can also install new scripts from inside the application with the press of a button.

  Im currently planning to add a syntax highlighter (even tough it didn't end well
  last time i tried) and a proper script repository where everyone can
  post theor own scripts and contribute to the project. In the meantime feel to create your
  own scripts and share them with me as im curious to see how bored people can get nowdays


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  python:
    plugin: python
    source: .
    python-packages:
      - certifi==2021.5.30
      - charset-normalizer==2.0.4
      - idna==3.2
      - pip==21.2.4
      - PyQt5-Qt5==5.15.2
      - PyQt5-sip==12.9.0
      - PyQt5==5.15.4
      - requests==2.26.0
      - setuptools==57.4.0
      - urllib3==1.26.6

  qnverter:
    plugin: make
    source: .
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18